version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_gpt4o_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src  # For development (optional)
